### PR TITLE
Add Cloud9 IDE to incubator list

### PR DESCRIPTION
**Pull request by sr229**
Adds Cloud9 IDE to the incubator list. This is the version of Cloud 9 IDE based from their Cloud9 Plugin SDK.

### CODE REVIEW

**Comment by staroider** [comment]
Wow! Thank @sr229  for adding a project here!

When we try the project, after successful launch, it shows username and password prompt of the browser.

image

We tried username and password from the launch dialog parameter, i.e. 

image

However, it shows "Invalid authorization header" on the screen.

image

We might missing something. Could you help us to try the project?

**Comment by sr229** [comment]
Based on my testing looks like setting the visibility of the app to public allows you to log in. Not sure what happened but I may ditch the authorization if there's built in access control already.

**Comment by staroider** [comment]
Got it. Confirmed that I can login correctly after make visibility public.
I think our ingress configuration may conflict with http basic auth in case of visibility is not public.
Let us quickly investigate this and update here.

(Of course It is up to you use enable/disable apps' own authorization)

**Comment by staroider** [comment]
@sr229 We investigated about "Invalid authorization header" error and found that Staroid authentication system does not handle when basic auth header is provided.  We just deployed the patch, so now it should work regardless of 'public' or 'private' of app visibility selection.

LGTM!

Regarding ditching in-app authentication, If an app is designed to handle multiple users in a single instance or need to use its own authentication system, then it make sense to keep in-app authentication. Otherwise turning it off gives 1 less step for user while Staroid already provides an access control. Decision is yours.

(A small tip. You can customize your project page https://staroid.com/g/sr229/c9-staroid. See [docs](https://docs.staroid.com/project/pages.html) and an [example](https://staroid.com/g/open-datastudio/jupyter)

Thanks again for adding this project!

**Comment by sr229** [comment]
Happy to hear that! I probably won't just ditch them since the ingress has been patched to properly send the headers.

**Pull request merged**
